autonomys/auto-drive

frontend/src/app/page.tsx
frontend/src/components/Files/FileDropZone.tsx
frontend/src/components/Files/UploadingObjects.tsx
frontend/src/models/UploadedObjectMetadata.ts

Adds observability on the progress of publishing the file/folder onchain.

Object Uploading Status

---

backend/src/server.ts
backend/src/services/uploadManager/index.ts
backend/src/utils/index.ts
backend/src/utils/safe.ts

Upload manager gets stuck sometimes

fix: upload manager reliability

---

frontend/src/components/common/ScopeSwitch.tsx

Scope switch based purely on the localStorage reactiveness didn't work well. I used an intermediate react state for enhancing how it works

Fix scope switch

---

README.md

This pull request includes updates to the `README.md` file to rebrand the project and provide a clearer description of its features and components.

Update README.md with clearer description

---

nginx/backend.conf
nginx/nginx.conf

Adding nginx configs for auto-drive
- mainly CORS configurations

add nginx configs

---

backend/src/controllers/object.ts
backend/src/utils/safe.ts

Some characters are forbidden in file download so this parser should be used

Fix download content disposition

---

backend/src/controllers/object.ts
backend/src/models/object.ts
backend/src/repositories/metadata.ts
backend/src/useCases/files.ts
backend/src/useCases/object.ts
frontend/src/app/drive/search/[cid]/page.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/models/ObjectSearchResult.ts
frontend/src/services/api.ts

Enable users to search files by their name through the search bar

Search by files by name 

---

backend/src/repositories/metadata.ts
backend/src/repositories/ownership.ts
frontend/src/app/drive/layout.tsx
frontend/src/app/drive/metadata/[cid]/page.tsx
frontend/src/app/drive/page.tsx
frontend/src/app/drive/profile/page.tsx
frontend/src/app/drive/search/[cid]/page.tsx
frontend/src/app/globals.css
frontend/src/components/ApiKeysTable/ApiKeyCreationModal.tsx
frontend/src/components/ApiKeysTable/index.tsx
frontend/src/components/Files/Metadata.tsx
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/components/RoleProtected/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/UploadedObjectInformation/index.tsx
frontend/src/components/UserEnsurer/index.tsx
frontend/src/components/UserTable/UserTableRow.tsx
frontend/src/components/common/DeleteFilesTable/index.tsx
frontend/src/components/common/FileTable/index.tsx
frontend/src/components/common/ScopeSwitch.tsx
frontend/src/middleware.tsx

Should solved #56, #50, #55, #54

Small fixes from UI

---

frontend/src/services/upload.ts

I did introduce this error during #72

Fix chunk index counter in file upload by chunks

---

backend/src/repositories/objects/metadata.ts
backend/src/repositories/objects/ownership.ts
backend/src/useCases/objects/object.ts
frontend/src/app/drive/global/page.tsx
frontend/src/app/drive/layout.tsx
frontend/src/app/drive/profile/page.tsx
frontend/src/app/onboarding/page.tsx
frontend/src/components/Files/FileDropZone.tsx
frontend/src/components/Files/ObjectDeleteModal.tsx
frontend/src/components/RemainingCreditTracker/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/SharedFiles/index.tsx
frontend/src/components/TrashFiles/index.tsx
frontend/src/components/common/ConditionalRender.tsx
frontend/src/components/common/FileTable/index.tsx

It's mostly composes of UI Fixes:
* Update progress bar styling in credit limit tracker
* Added a log-out button
* Added global feed view
* Removed header scope switcher
* Translated header search bar into `global feed` and `my files` view
* Conditional rendering of buttons (e.g Not show remove button in the Trash view)
Some other fixes
* Restore file action didn't considered owner a user that marked a file as delete
* Search by cid or name with user scope did include shared files and that's not the desired behaviour

Small updates on the UI

---

frontend/src/app/api/auth/[...nextauth]/config.ts

In the refresh token PR I break accidentally discord oauth due to removal of accessToken setup

Fix discord auth

---

backend/src/services/download/databaseDownloadCache/index.ts

I was comparing a Number with a BigInt resulting in an error. Solved by casting to BigInt

Fix wrong BigInt & Number management

---

frontend/src/app/onboarding/page.tsx
frontend/src/components/common/Disclaimer.tsx

Simplifies the onboarding view from multiple to single step. More details in this [issue](https://github.com/orgs/autonomys/projects/32?pane=issue&itemId=87687717&issue=autonomys%7Cauto-drive%7C102)

Update onboarding page terms & conditions

---

nginx/backend.conf
nginx/nginx.conf

Update of nginx config for adding support to hasura. 
Main changes added: 
- Added /hasura location pointing to localhost:6565
- Updated / location to /api
- Update root add_header policies in ngnix.conf to be inside /location (and simplified the OPTIONS handle)

update: nginx setup

---

frontend/gql/graphql.ts
frontend/src/components/Files/ObjectDeleteModal.tsx
frontend/src/components/Files/ObjectDownloadModal.tsx
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/components/Files/UploadingObjects.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/common/FileTable/index.tsx
frontend/src/views/GlobalFiles/index.tsx
frontend/src/views/SharedFiles/index.tsx
frontend/src/views/SharedFiles/utils.ts
frontend/src/views/TrashFiles/index.tsx
frontend/src/views/UserFiles/index.tsx
frontend/src/views/UserFiles/query.ts

Between pagination updates the table was not showing any loading spinner and just the previous page. I added a loading spinner and some little improvements.

Improve loading table

---

docker-compose.dev.yml
docker-compose.prod.yml

Database URL was misconfigurated in the docker-compose.dev.yml. 
Additionally, health check also pointed the wrong the endpoint

fix: docker compose dev config

---

backend/src/config.ts

Updates default value of allow cors for enabling ignoring header addition

Make AllowCors=undefined default

---

frontend/src/components/FAQ/index.tsx
frontend/src/views/Home/index.tsx

Landing was not displaying nicely in mobile this improves it

update: optimize landing for mobile

---

docker-compose.prod.yml

Missing to pass environment variables

fix: docker compose setup

---

backend/src/drivers/ws.ts
backend/src/services/download/index.ts
backend/src/services/dsn/objectMappingListener/index.ts
backend/src/services/upload/nodeMigrator/index.ts
backend/src/services/upload/onchainPublisher/index.ts
backend/src/services/upload/onchainPublisher/transactionManager.ts
backend/src/useCases/objects/nodes.ts

I setup as `error` log level some logs that were not intended to be so. I updated to the correct level.

fix: some logger level

---

backend/src/drivers/pg.ts

Connection string does not allow to allow unauthorized

update: pg driver

---

backend/__tests__/e2e/uploads/files.spec.ts
backend/migrations/20250120190642-remove-user-management-fks.js
backend/src/services/download/databaseDownloadCache/index.ts
backend/src/services/upload/nodeRemover/index.ts

Populate files caches on object archival

feat: populate cache on archival

---

backend/src/controllers/object.ts
backend/src/controllers/subscriptions.ts
backend/src/controllers/upload.ts
backend/src/utils/express.ts

Similarly to https://github.com/autonomys/auto-files-gateway/pull/20, async errors are not handled by error middleware so async request handlers are wrapped with a await try/catch structure.

Update handle async errors in request handlers

---

frontend/src/app/[chain]/drive/fs/[cid]/page.tsx
frontend/src/app/[chain]/page.tsx
frontend/src/app/onboarding/page.tsx
frontend/src/components/Files/Metadata.tsx
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/components/NodeExplorer/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/common/FileCard.tsx
frontend/src/components/common/FileTable/FileTableRow.tsx
frontend/src/views/FileSystem/index.tsx
frontend/src/views/ObjectDetails/index.tsx
frontend/src/views/SearchResult/index.tsx
frontend/src/views/UserFiles/index.tsx

Should solve the issue at #148 and several navigation issues. I'll include in another PR tomorrow the 404 page

Fix navigation after multi-chain

---

frontend/package.json
frontend/src/app/onboarding/page.tsx
frontend/src/components/FilePreview/FolderPreview.tsx
frontend/src/components/FilePreview/NoPreviewAvailable.tsx
frontend/src/components/FilePreview/index.tsx
frontend/src/components/Files/Metadata.tsx
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/components/NodeExplorer/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/UploadedObjectInformation/index.tsx
frontend/src/components/common/Arguments.tsx
frontend/src/components/common/FileCard.tsx
frontend/src/components/common/FileTable/FileTableRow.tsx
frontend/src/constants/routes.ts
frontend/src/views/FileSystem/index.tsx
frontend/src/views/ObjectDetails/index.tsx
frontend/src/views/Onboarding/index.tsx
frontend/src/views/SearchResult/index.tsx
frontend/src/views/UserFiles/index.tsx
frontend/yarn.lock

Added JSON file preview and removed former viewer for native `<object>` tag

Improve file preview

---

frontend/src/app/[chain]/[...not-found]/page.tsx
frontend/src/app/[chain]/layout.tsx
frontend/src/views/NotFound/index.tsx

Added a fallback 404 page in case a route is mispelled within `/[chain]/**` route

update: add 404 page

---

frontend/src/components/UserEnsurer/index.tsx
frontend/src/contexts/network.tsx
frontend/src/states/user.ts

With multi-chain update I forgot to implement subscription retrieval

fix: empty susbcription info

---

frontend/src/components/common/FileTable/FileTableRow.tsx

Solves #133 adding a link to object details for files (or folders) within a folder

update: add object details link to children cids

---

frontend/src/components/FilePreview/index.tsx
frontend/src/components/UploadedObjectInformation/index.tsx
frontend/src/components/common/Arguments.tsx

Add background to FilePreview regardless if its JsonViewer or object

chore: ui change

---

docker-compose.prod.yml

add new relic agent to monitor docker stack and provide container metrics

add new relic to monitor docker stack

---

backend/src/controllers/object.ts

Removed auth check for public download link

Fix some small issues with public links

---

frontend/codegen.ts
frontend/gql/graphql.ts
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/components/UploadedObjectInformation/index.tsx
frontend/src/models/UploadedObjectMetadata.ts
frontend/src/services/api.ts
frontend/src/services/gql/common/query.ts
frontend/src/services/gql/utils.ts
frontend/src/views/GlobalFiles/utils.ts
frontend/src/views/SharedFiles/utils.ts
frontend/src/views/TrashFiles/utils.ts
frontend/src/views/UserFiles/index.tsx
frontend/src/views/UserFiles/query.ts
frontend/src/views/UserFiles/utils.ts

Implement in frontend downloadable links

Add downloadable links

---

backend/src/config.ts
backend/src/useCases/users/subscriptions.ts

Added some envars for controlling default subscription values

Make default upload/download limits configurable 

---

frontend/src/components/RemainingCreditTracker/index.tsx

Previous display was not to noticeable

Make ask for more credits button more striking

---

backend/.gitignore
backend/src/awsSetup.ts
backend/src/server.ts
backend/start-server.sh
docker-compose.prod.yml

Mainnet environment has two issues to be solved: 
- Secrets not being retrieved 
- Migrations `pg` driver won't connect correctly

fix: production environment

---

frontend/src/app/[chain]/layout.tsx

Fetching user not loading correctly

fix: user not loaded correctly

---

backend/src/services/dsn/fileGateway/index.ts
backend/src/useCases/objects/files.ts
backend/src/utils/async.ts

I thought that http solution wouldn't handle compression but it does so there was no point on using it

update: dsn fetching

---

frontend/src/components/common/FileTable/FileTableRow.tsx

https://github.com/user-attachments/assets/0becf6c6-5a97-42bf-a978-4de8f7c0c2e9
https://github.com/user-attachments/assets/5734e3c1-caf3-43ad-a95e-6b1e9b61a25e

fix(ui): 🐛 file/folder table list checkbox behave wired while checking/unchecking

---

frontend/src/app/layout.tsx

fix(ui): 🐛 Social share image url

---

backend/__tests__/e2e/uploads/files.spec.ts
backend/__tests__/e2e/uploads/folder.spec.ts
backend/src/config.ts
backend/src/controllers/object.ts
backend/src/services/auth/express.ts
backend/src/useCases/objects/files.ts
backend/src/useCases/objects/object.ts
backend/src/utils/async.ts

This PR enables to allow anonymous downloads if so is determined by envar. This would allow to deploy one instance with public downloads.

Enable public downloads

---

backend/src/api.ts
backend/src/config.ts
backend/src/controllers/object.ts
backend/src/drivers/substrate.ts
backend/src/services/auth/express.ts
backend/src/services/download/express.ts
backend/src/services/download/fsCache/index.ts
backend/src/services/download/fsCache/singleton.ts
backend/src/services/dsn/fileGateway/index.ts
backend/src/services/dsn/objectMappingListener/index.ts
backend/src/services/upload/onchainPublisher/accounts.ts
backend/src/useCases/objects/files.ts
backend/src/useCases/users/subscriptions.ts
backend/src/utils/async.ts
docker-compose.devProdAuth.yml

Some small updates:
- Unwrap async iterable consumer in `forkAsyncIterable` method
- Add `OPTIONAL_AUTH` environment variable
- Cache: 
-  Custom serialisation for BigInt
-  Fix inconsistent state due to parallel caches set execution.
-   Extract download response headers to common function
- Re-structure config 
- Add limit to anonymous downloads

Small updates

---

backend/src/services/dsn/fileGateway/index.ts

I restructured the configuration names for improve readability and I forgot to update some references 🫠

fix: base url dsn gateway

---

backend/src/controllers/object.ts
backend/src/services/download/express.ts

Front-end doesn't trigger a download if attachment is not set

update: conditionally set content disposition

---

frontend/package.json
frontend/src/components/Files/ObjectShareModal.tsx
frontend/src/services/api.ts
frontend/yarn.lock

Use auto-drive SDK methods for shareable download link

update: use sdk tools for shareable download link

---

backend/src/controllers/object.ts

I added this endpoint because would be hepful for implementing some features in auto-drive sdk

feat: add get summary endpoint

---

examples/.env.test
examples/simple-cli/commands/download.ts
examples/simple-cli/commands/publish.ts
frontend/package.json
frontend/src/services/api.ts
frontend/src/services/upload.ts
frontend/yarn.lock

New package used in auto-drive (yet not published)

Use new version of auto-drive

---

docker-compose.dev.yml
docker-compose.devProdAuth.yml
docker-compose.prod.yml
frontend/gql/graphql.ts
frontend/package.json
frontend/src/components/common/FileTable/FileTableRow.tsx
frontend/src/components/common/FileTable/index.tsx
frontend/src/models/UploadedObjectMetadata.ts
frontend/src/utils/time.ts
frontend/src/views/GlobalFiles/index.tsx
frontend/src/views/GlobalFiles/query.graphql
frontend/src/views/GlobalFiles/utils.ts
frontend/src/views/SharedFiles/index.tsx
frontend/src/views/SharedFiles/query.graphql
frontend/src/views/SharedFiles/utils.ts
frontend/src/views/TrashFiles/index.tsx
frontend/src/views/TrashFiles/query.graphql
frontend/src/views/TrashFiles/utils.ts
frontend/src/views/UserFiles/index.tsx
frontend/src/views/UserFiles/query.graphql
frontend/src/views/UserFiles/utils.ts
frontend/yarn.lock
hasura/metadata/databases/default/tables/root_metadata.yaml
hasura/metadata/databases/default/tables/tables.yaml
hasura/migrations/default/1739554139049_add-root-metadata/down.sql
hasura/migrations/default/1739554139049_add-root-metadata/up.sql

Files were showing with an arbitrary sorting, this gave bad UX. Now it sorted descending in upload date (latest uploads first).
Additionally, I removed owner column and substituted by upload date. The prior approach for getting root_metadata couldn't be filtered so I had to change the approach using other Hasura features.

update: add default sorting

---

backend/__tests__/e2e/uploads/files.spec.ts
backend/src/services/download/fsCache/index.ts
backend/src/services/download/index.ts
docker-compose.prod.yml

Just like https://github.com/autonomys/auto-files-gateway/pull/28 improved cache setup

update: improve caching setup

---

docker-compose.prod.yml

With #201, I introduced other error that didn't allow to access to entrypoint

fix: volumes configuration

---

frontend/src/components/FileTables/GlobalFiles/index.tsx
frontend/src/components/FileTables/SharedFiles/index.tsx
frontend/src/components/FileTables/TrashFiles/index.tsx
frontend/src/components/FileTables/UserFiles/index.tsx
frontend/src/components/FileTables/common/FileDropZone.tsx
frontend/src/components/FileTables/common/FileTable/SortableTableColumn.tsx
frontend/src/components/FileTables/common/FileTable/index.tsx
frontend/src/components/FileTables/state.tsx
frontend/src/components/RoleProtected/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/common/Table/TableHead.tsx
frontend/src/middleware.tsx
frontend/src/services/download.ts

Added sorting to files table by name or date both descending or ascending

Add sorting to files table

---

backend/Dockerfile
backend/src/controllers/upload.ts
docker-compose.prod.yml

Volumes were not the correct approach for having backend folder but workdir in Dockerfile.

fix: docker file workdir

---

frontend/src/components/SearchBar/index.tsx

Search bar in "My files" search within your files but the placeholder didn't reflect this

update: search placeholder

---

frontend/gql/graphql.ts
frontend/src/components/FileTables/TrashFiles/query.graphql
frontend/src/components/FileTables/common/FileTable/index.tsx
frontend/src/components/common/Table/TableBody.tsx
frontend/src/components/common/Table/TableHead.tsx
frontend/src/components/common/Table/index.tsx

In medium screens table occupied more than `100vw` overflowing at the right of the screen. I've added an horizontal scrolling to the table.
Additionally, I fixed a query that was not working

Fix table overflow behaviour

---

auth/src/services/authManager/providers/custom.ts

Update jwt expiration time

---

backend/src/drivers/vmetrics.ts
backend/src/http/middlewares/requestTrace.ts
backend/src/useCases/objects/interactions.ts

Added metric for keeping track of the size of the uploads

feat: send interaction to vmetrics

---

backend/src/docs/view.ts
backend/src/drivers/vmetrics.ts
backend/src/http/controllers/docs.ts
backend/src/repositories/objects/interactions.ts

The prod setup has the namespace /api in the http path so this code is invalid

fix: raw url get

---

gateway/Dockerfile

Adds a Dockerfile for launching multi-network gateway

feat: add gateway dockerfile

---

frontend/src/components/Home/index.tsx
frontend/src/constants/routes.ts

Added docs link to landing page

chore: add docs link to mainpage

---

nginx/backend.mainnet.file-gateway.conf
nginx/backend.mainnet.private.conf
nginx/backend.mainnet.public.conf
nginx/backend.taurus.private.conf
nginx/backend.taurus.public.conf
nginx/hasura.conf
nginx/nginx.conf

- add backend configurations for each entity
- add rate-limiting to protect from abuse

add AD data access layer nginx configs

---

gateway/public/index.html
gateway/src/index.ts

feat(ui): ✨ branded landing page for `gateway.autonomys.xyz`

---

frontend/README.md
frontend/src/app/[chain]/layout.tsx
frontend/src/components/FileTables/GlobalFiles/index.tsx
frontend/src/components/FileTables/SharedFiles/index.tsx
frontend/src/components/FileTables/TrashFiles/index.tsx
frontend/src/components/FileTables/UserFiles/index.tsx
frontend/src/components/FileTables/common/FileTable/SortableTableColumn.tsx
frontend/src/components/FileTables/common/FileTable/TablePaginator.tsx
frontend/src/components/FileTables/common/FileTable/TableRouteChangeListener.tsx
frontend/src/components/FileTables/state.tsx
frontend/src/constants/table.ts
frontend/src/hooks/useRouteChange.ts
frontend/src/utils/table.ts

https://github.com/user-attachments/assets/eb4965af-e099-4d68-941c-5d9bfd174de3
closes: #286

feat(ui): ✨ add query params when table params change

---

docker-compose.prod.yml

Use docker image in production env

update: use docker image in production env

---

frontend/src/components/FileTables/common/FileTable/TablePaginator.tsx
frontend/src/utils/table.ts

feat(ui): ✨ Add page selector in table navigation

---

docker-compose.prod.yml

Add Loki logging configuration to production Docker Compose

feat: add Loki logging configuration to production Docker Compose

---

frontend/src/components/ObjectDetails/FilePreview/index.tsx
frontend/src/components/UploadedObjectInformation/FileIcons.tsx
frontend/src/components/UploadedObjectInformation/index.tsx
frontend/src/utils/number.ts

feat(ui): ✨  improve file/folder details page

---

frontend/gql/graphql.ts
frontend/src/components/FileTables/GlobalFiles/index.tsx
frontend/src/components/FileTables/GlobalFiles/query.graphql
frontend/src/components/FileTables/UserFiles/index.tsx
frontend/src/components/FileTables/UserFiles/query.graphql
frontend/src/components/FileTables/common/FileTable/FileTableRow.tsx
frontend/src/components/FileTables/state.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/hooks/useDebounce.ts
frontend/src/utils/time.ts

fix(ui): 🎨  update auto drive table date and searchbar

---

frontend/gql/graphql.ts
frontend/src/components/FileTables/GlobalFiles/query.graphql
frontend/src/components/FileTables/UserFiles/query.graphql
frontend/src/components/FileTables/state.tsx

fix(ui): 🐛 adjust page number and page count when searching file

---

auth/migrations/sqls/20250429134858-add-username-down.sql

Fixed wrong target table in down migration

fix: auth down migrations

---

backend/src/repositories/objects/nodes.ts

Silly bug in the retrieval of the last archived piece

fix: last archival query

---

backend/__tests__/e2e/uploads/files.spec.ts
backend/__tests__/e2e/uploads/folder.spec.ts
backend/__tests__/unit/OnchainPublisher.spec.ts
backend/src/config.ts
backend/src/services/taskManager/index.ts
backend/src/services/taskManager/tasks.ts
backend/src/services/upload/onchainPublisher/index.ts
backend/src/useCases/objects/nodes.ts
backend/src/useCases/uploads/uploads.ts
backend/src/utils/safe.ts
backend/src/worker.ts

Add a limit to the times a task is tried to be executed

feat: add max retries to task manager

---

docker-compose.dev.yml
docker-compose.devProdAuth.yml
docker-compose.prod.yml

* Wrong dependency service name: backend -> backend-api
* No `3000:3000` port mapping for worker nor healthcheck

Fix prod docker compose config

---

frontend/src/middleware.tsx

Refreshing token is needed when access token is outdated but no refreshing is triggered in middleware component since it gets the token from the http request.

fix: re-login required after 1h

---

backend/src/docs/reference/downloads.ts
backend/src/docs/reference/index.ts
backend/src/docs/reference/objects.ts
backend/src/docs/reference/servers.ts
backend/src/docs/reference/subscriptions.ts
backend/src/docs/reference/uploads.ts

This PR includes the following doc updates:
* Correct service separation between Auto-Drive API and Download Gateway
* More thoroughly explanation on auth management.

Doc updates

---

frontend/src/app/layout.tsx

Web3Provider uses wallet-connect package that underlying is using indexedDB that is not accesible in the server side. Adjusting the provider to be dynamic and avoiding SSR should be enough to solve the issue.

Fix wallet provider management

---

frontend/src/app/api/auth/[...nextauth]/jwt.ts
frontend/src/components/FileTables/common/FileTable/TableRouteChangeListener.tsx
frontend/src/components/FileTables/common/UploadingFileModal.tsx
frontend/src/services/download.ts
frontend/src/utils/indexedb.ts

The [previous PR](https://github.com/autonomys/auto-drive/pull/385) was insufficient for keeping the server to access the IndexedDB interface, so I now handle the rejection of the promise of database creation. 
Additionally, I removed some unused logs

Avoid IndexedDB access from server environments

---

backend/package.json
backend/src/useCases/objects/files.ts
yarn.lock

Implements [this change](https://github.com/autonomys/auto-sdk/pull/428) from `@autonomys/auto-files`

chore: update SDK to v1.5.1

---

backend/src/config.ts

Files were expiring in the cache after 10 days

update: cache TTL to disable expiration in config

---

backend/package.json
yarn.lock

Introduces [this fix](https://github.com/autonomys/auto-sdk/pull/430)

chore: update sdk

---

frontend/package.json
frontend/src/app/layout.tsx
frontend/src/components/FileTables/common/FileTable/FileTableRowSkeleton.tsx
frontend/src/components/FileTables/common/FileTable/index.tsx
frontend/src/components/FileTables/state.tsx
frontend/src/components/common/InternalLink.tsx
yarn.lock

Improve loading by:
- Add loading bar at the top when navigating
- Add table skeleton instead a spinner that shrinks the table visualisation
- Handle correctly double clicking in next button by ignoring the result of the first hit

Improve loading ux

---

gateway/docker-compose.prod.yml

Adds prod logging to multi-network gateway

feat: add prod logging to gateway

---

.github/workflows/image-generations.yml

Added support for build snapshots

feat(ci/cd): add support for not production release

---

nginx/all.staging-mainnet.conf
nginx/all.staging-taurus.conf

Added nginx configuration for staging environments

Nginx staging configuration

---

backend/src/infrastructure/services/download/memoryDownloadCache/index.ts

Testing S3 compatibility layer in staging environment I detected this error that was failing to cache correctly files in memory cache leading to download errors.

Fix memory cache population

---

apps/backend/src/core/objects/object.ts
apps/backend/src/core/uploads/uploads.ts
apps/backend/src/infrastructure/eventRouter/index.ts
apps/backend/src/infrastructure/eventRouter/processors/download.ts
apps/backend/src/infrastructure/eventRouter/tasks.ts
apps/backend/src/infrastructure/services/download/index.ts
docker-compose.prod.yml

The volume mount path was configured due to introduction of `apps/` folder. 
Update to match the actual target `fsCache` path
Additionally, cache population now happens during file upload instead of file archival. This change eases the handling of potential race conditions, which are already managed correctly but could become problematic if updated incorrectly.

Fix cache management

---

apps/backend/src/app/apis/download.ts
apps/backend/src/app/apis/frontend.ts
apps/backend/src/app/controllers/features.ts
apps/backend/src/app/servers/frontend.ts
apps/backend/src/app/servers/frontendWorker.ts
apps/backend/src/config.ts
apps/backend/src/core/featureFlags/express.ts
apps/backend/src/core/featureFlags/index.ts
apps/backend/src/infrastructure/eventRouter/tasks.ts
apps/frontend/src/components/atoms/AskForCredits.tsx
apps/frontend/src/components/atoms/SessionEnsurer.tsx
apps/frontend/src/components/organisms/SideNavBar/index.tsx
apps/frontend/src/globalStates/user.ts
apps/frontend/src/services/api.ts

We want to safely rollout the buy credits feature in a progressive manner
This PR implements a environment variable based feature flagging system that has three posibles states:
- Active For All
- Active For Employees (via allowlisted of domains)
- Disabled
- Introduced `/features` controller that given authorization params it returns available features
- Environment-based variables with two fields 'active' and `employeeOnly`

Buy credits feature flagging (#5)
