- backend/src/repositories/ownership.ts
If a user uploaded the same file twice the former query failed, now the entry is replaced by the new forcing to be marked as not deleted
> Fix handle ownership duplicates

- frontend/src/components/common/ScopeSwitch.tsx
The `global` state was not init correctly and led to wrong representation of the scopeSwitch
> Fix scope switch init value

- backend/src/useCases/files.ts
Metadata was saved as it was processed in `processTree` but I changed this because I wanted to group by UploadCID and make the operation atomic too. For this I forwarded all the children metadata of an folder (including the children of children nodes) so the operation is atomic and could be grouped. The issue is that the field `metadata` includes children of children, that are not meant to be at the `childrenMetadata` of a folder's off-chain metadata.
Additionally, there was some bug generating the `zip` file
> Fix metadata creation for zip download

- frontend/src/app/drive/page.tsx
- frontend/src/app/drive/shared/page.tsx
- frontend/src/app/drive/trash/page.tsx
- frontend/src/components/Files/Metadata.tsx
- frontend/src/components/SharedFiles/index.tsx
- frontend/src/components/TrashFiles/index.tsx
- frontend/src/components/common/DeleteFilesTable/index.tsx
- frontend/src/components/common/FileTable/index.tsx
- frontend/src/components/common/Table/TableFooter.tsx
- frontend/src/components/common/TablePaginator/index.tsx
- frontend/src/models/UploadedObjectMetadata.ts
- frontend/src/models/common.tsx
- frontend/src/services/api.ts
- frontend/src/utils/file.ts
- frontend/tailwind.config.ts
Solves issue #69 
- Creates table paginator
- Paginates getRoots, getShareRoots, getDeletedRoots requests. 
- The type of these methods has been updated from CIDs (that posteriorly were one by one fetch its metadata) to ObjectSummary that basically composes only the needed data for table representation
> Improve files fetching

- frontend/src/app/drive/page.tsx
After implementing pagination and batching for files fetching in #76, there was an error when `TablePaginator` provoked a refetch of file list (by updating either `pageSize` or `currentPage`). What happened is that a change of state in the child provoked an update in the parent's state for breaking this loop, it's needed an intermediary state `setRootObjectMetadata(null)`
> Fix "rendered fewer hooks than expected" error

- frontend/src/app/drive/page.tsx
In a previous PR I updated the height of FileDropZone this led to a not too nice UI display. I updated to this interface:
> fix: search bar display

- backend/src/repositories/uploads/blockstore.ts
- backend/src/useCases/objects/nodes.ts
- backend/src/useCases/uploads/blockstore.ts
When a file is uploaded the IPLD nodes are generated and saved in a temporary table (`uploads.blockstore`) when the upload is completed by the user these nodes are migrated to the persistent table (`public.nodes`). 
If a user tries to fetch the file when this migration is not completed the fetch failed. This should fix that by searching in the temp table if the persistent table fails.
> Fix missing chunk during migration

- frontend/src/components/FAQ/index.tsx
I actually thought there were no questions/answers, but then I realized that it was just because the question text was white, like the background of the box.
This PR makes sure the color of the text is dark.
Some classes refer to dark: and use specific brand colors not defined in tailwind.config...
(This PR does not address these issues, since the design does not have a dark/light switch anyway)
> Make sure the color of the FAQ question are dark

- frontend/src/views/GlobalFiles/utils.ts
Due to the node removal after the archival of a file some dependencies with `transaction_results` are making the view of global files to crash. 
For fixing this we just have to make optional some of these relationships.
> fix: global files view fail when files are archived

- auth/migrations/sqls/20250120110354-init-schema-down.sql
- auth/migrations/sqls/20250120110354-init-schema-up.sql
- auth/package.json
- auth/src/controllers/http/user.ts
- auth/src/controllers/user.ts
- auth/src/drivers/pg.ts
- auth/src/index.ts
- auth/src/lambda.ts
- auth/src/services/authManager/providers/custom.ts
- auth/yarn.lock
- Updates JWT secret signing schema from `HS256` to `RS256` for enabling verifiers to not have the secret key but the pubkey.
- Creates an entrypoint with `serverless-http` that translates a `express` application into a lambda-interfaced app.
- Updates `pg` driver for dynamically connect to either AWS DSQL or standard postgres.
> feat: add support for lambda deployment

- backend/src/services/download/fsCache/singleton.ts
Was missing the extension in an import. I'll research into some solution to make it fail on build-time
> fix: import missing .js extension

- backend/__tests__/e2e/users/credits.spec.ts
- backend/migrations/20250127141651-delete-download-cache-schema.js
- backend/src/services/dsn/fileGateway/index.ts
When http receives a `Content-Encoding: deflate` it automatically decompresses. Since the SDK manages decompression some issues were raised due to intended double decompression. 
Enabling a raw download makes the SDK the unique responsible for decompression.
> update: use gateway raw mode

- .env.dev
- auth/.dockerignore
- auth/.env.sample
- auth/Dockerfile
- auth/package.json
- auth/src/config.ts
- auth/src/services/authManager/providers/custom.ts
- auth/yarn.lock
- backend/.dockerignore
- backend/Dockerfile
- backend/yarn.lock
- docker-compose.dev.yml
- docker-compose.devProdAuth.yml
- docker-compose.prod.yml
- frontend/.gitignore
- package.json
Separates docker compose in three:
- production: not public
- dev using prod auth: not public 
- dev using local auth: Public env file
Additionally, it enables an environmental variable (`JWT_SECRET_ALGORITHM`) for choosing the jwt secret encryption schema. Enabling having symmetric schemas for dev environments and asymmetric for production.
> update: improve docker setup

- docker-compose.prod.yml
The instance of RabbitMQ in testnet will be in docker-compose whereas in mainnet will be on a standalone server. This change is needed for enabling those use cases.
> Update production setup

- backend/Dockerfile
After #198 update the Dockerfile was not working correctly since the `curl` was not default in base image and it was used in healthcheck.
> Fix dockerfile after update

- backend/src/useCases/uploads/blockstore.ts
- backend/src/useCases/uploads/uploads.ts
Folder uploads consists of several linked uploads where node publishing doesn't occurr until the whole upload is finished. 
After the update of the message-based uploads within a folder were being migrated, this shouldn't occur until the whole upload is uploaded and parsed into IPLD nodes. For solving this, we should just ensure the scheduling of node migration is only emitted once the root upload is finished and processed.
> fix: folder upload

- auth/src/services/authManager/providers/custom.ts
- frontend/src/app/api/auth/[...nextauth]/config.ts
@jfrank-summit reported that sessions in auto-drive were lasting an hour only though the refreshing token was setup  to 7-day-long. 
Refreshing access token was not managed correctly now every time a session called is made by the user a refreshing in intended (in the case access token is to expired)
> fix: session lasting hour

- backend/src/api.ts
- backend/src/config.ts
- backend/src/drivers/vmetrics.ts
- backend/src/http/controllers/object.ts
- backend/src/http/controllers/subscriptions.ts
- backend/src/http/controllers/upload.ts
- backend/src/http/middlewares/requestTrace.ts
- frontend/.yarnrc.yml
This will allow us to obtain metrics about the performance of auto-drive's request so we could make better decisions.
To Reviewers:
- This [file](https://github.com/autonomys/auto-drive/pull/215/files#diff-34d0b2d40c6eb707c9b07269305407202117e4a6f19e1772551cf8ef881c0cd4) is the major change
- I added http at root level including `middlewares` and `controllers`
- Copied VMetrics driver from [auto-files-gateway](https://github.com/autonomys/auto-files-gateway/blob/004e1bf1470e8bc0e4c30e5a117f2a46684e967a/services/file-retriever/src/drivers/metrics.ts)
> Add vmetrics for request tracing 

- backend/src/services/download/express.ts
The issue is that we conditionally manage compression on the server depending on whether is the requester is the SDK or not. This is because the SDK was responsible of managing encryption & compression but chrome for showing the file needs to be decompressed or marked with header Content-Encoding: deflate;
The detection of the requester type was not correctly since `Sec-Fetch-Dest` didn't determine it in all cases.
[Sec-Fetch-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Site#none) explains the relationship between a request initiator's origin and the origin of the requested resource, being `none` when there is not initiator.
Anyways, I'll create an issue for improving the compression handling of auto-drive's both backend & SDK.
> fix: encoding handling

- backend/src/api.ts
- backend/src/config.ts
- backend/src/drivers/vmetrics.ts
- backend/src/http/middlewares/requestTrace.ts
- backend/src/utils/express.ts
- docker-compose.devProdAuth.yml
The usage of middleware was provoking duplicated headers sent. With this setup we avoid that behavior.
Also, I unified the monitoring object with `auto-files-gateway`
> fix: request tracing

- backend/__tests__/e2e/users/credits.spec.ts
- backend/src/http/middlewares/requestTrace.ts
- backend/src/repositories/objects/interactions.ts
- backend/src/services/download/express.ts
Encoding management of downloaded files has been a bit of an issue since we were conditionally encoding depending on user request headers.
I'm implementing a set of PRs within Auto-Drive repo's for improve the way we handle this complexity. For prior versions of our SDK we don't have a better approach than relying on headers though for newer versions this won't be an issue anymore.
> Improve encoding management

- frontend/src/app/api/auth/[...nextauth]/config.ts
Default next auth config is for cookies to persist during session, this means that if a user closes the tab the user should re-login. 
I like the experience of not having to re-login when a session token still valid. I updated the liveliness of the session token to make it equal to the liveliness of the refresh token.
> update: session cookies maxAge

- frontend/src/components/FileTables/common/ObjectShareModal.tsx
Double slash (`//`) was introduced in this copy button
> Fix share details generation

- backend/src/services/download/express.ts
I've discovered that exists this case in which the document should be rendered as a document
> fix: checking downloading headers

- backend/__tests__/e2e/uploads/files.spec.ts
- backend/__tests__/e2e/uploads/folder.spec.ts
- backend/src/useCases/uploads/uploads.ts
- package.json
Nodes were published just after being migrated from the temporary table to the persistent table. 
For avoiding that illegitimate uploads get to into the DSN the node publishing tasks are scheduled once the processing of the tags has been completed.
> update: node publishing life cycle

- frontend/src/app/api/auth/[...nextauth]/config.ts
If you enter into auto-drive after having logged in after less than 7 days shouldn't require a re-login
> fix: session not being persistent

- frontend/src/components/Home/index.tsx
The middleware uses `getToken` next-auth method for retrieving the session information of the request user. The root cause of the issue is that `getToken` method doesn't refresh the session if needed making the call to `checkAuth` to fail.
For ensuring no authentication is asked before refresh token expiration a session refresh is forced on the landing page.
> fix: refresh session on landing page

- backend/src/repositories/objects/metadata.ts
- backend/src/useCases/objects/object.ts
Sometimes nodes are already removed but the download is tried causing the file download to fail and re-executing the full batch again
> Ignore download error on archiving

- backend/src/services/upload/onchainPublisher/index.ts
Discarding duplicated nodes led to misreading the results. Just updating to `filteredNodes` fix it
> Fix uploading nodes

- backend/__tests__/e2e/objects/nodes.spec.ts
- backend/src/useCases/objects/object.ts
Now on object archival the auto-drive cache is populated from DB file re-construction and the is forced a download in files gateway for populating their cache. 
This is because we'd want the public instance (the one used by `gateway.autonomys.xyz`) to have the object cached but the upload is done via the private one.
> update: cache populating policy

- frontend/src/constants/networks.ts
- frontend/src/contexts/network.tsx
This is for making the public instances the only responsible for caching files rather than having two servers with their own caching, leading to need two reads for populating boths caches.
> feat: separate download service

- docker-compose.prod.yml
Problem:
Container was port used by environment variable and it was mapped to the same variable. However, healthcheck was poiting to :3000
Solution:
All the services use :3000 in the container and are mapped to port determined by environment variable
> fix: port setup and health checks for workers

- backend/__tests__/unit/repositories/nodes.spec.ts
- backend/src/repositories/objects/nodes.ts
- backend/src/useCases/objects/object.ts
Previously we were removing nodes DB entries instead of just the `encoded_node` data when a file was archived but this had several problems as not having the node count of a file.
> update: do not remove nodes but just `encoded_node` field

- docker-compose.prod.yml
**Problem:**
Cache was not populated with new files since volume path was misconfigured leading to file system cache to be wiped after the update of the docker image.
**Solution:**
Setup correctly the cache path.
> fix: update backend volume paths

- backend/src/useCases/objects/object.ts
- backend/src/utils/misc.ts
- **Files gateway cache is not populated when a file is archived:** With the separation of **Frontend** and **Download** services there's no need to populate the **Files Gateway** since it was meant to be cached in there for being able to be retrieved by the public and the private instance regardless from which of these processed the archival. 
- **Consume readable stream:** Readable streams implement a `read` method that is called by nodejs when the stream is consumed, if it's not consumed read operations are not performed and therefore no caching happens.
> update: how caches are populated

- auth/migrations/20250620112629-indexes.js
- auth/migrations/sqls/20250620112629-indexes-down.sql
- auth/migrations/sqls/20250620112629-indexes-up.sql
- backend/migrations/20250620113124-indexes.js
- backend/migrations/sqls/20241002111606-init-schema-up.sql
- backend/migrations/sqls/20250620113124-indexes-down.sql
- backend/migrations/sqls/20250620113124-indexes-up.sql
**Description:**
Add some indexes for improving the following read operations: 
- **User by Public ID:** Every operation in the backend that is performed checks the user's by public id
- **Metadata by Head CID:** Metadata has a PK (root cid, head_cid) though most times metadata is fetched by `head_cid` since there's no need to know if the object is inside a folder.
- **Nodes by Head CID & Root CID:** Some operations for example `encoded_node` field removal are performed not by `cid` but for `root_cid` (this happens with `head_cid` as well) so having an index would increase the speed of these operations. 
- **Interactions by Subscription ID:**: There's basically one main operation in this table and it's to filter by `subscription_id` and `type` so having this index would improve the speed …
> feat: add indexes to db tables

- backend/src/useCases/objects/object.ts
This would solve #417. 
**Problem:**
Populating the cache asynchronously leads to a race condition where the removal of nodes (performed just after the file is populated in cache) starts before the end of the cache population leading to the error shown. 
**Solution:**
Awaiting for the file to be populated for nodes data to be wiped.
> Fix file cache population on object archived

- Makefile
@jfrank-summit You reported some issue on the past syncing, for already initialised workspaces the `init-submodules` would correctly keep up to date the latest pointer to submodules though would fail for not initialised workspaces.
> Fix submodules sync

- ansible/auto-drive-deployment.yml
Sometimes we will just want to re-deploy after making some changes in `.env` at infisical for this we wouldn't need to update any image, so this step is now skipped if no `image_tag` is defined.
> feat: enable no image update deployments

- backend/migrations/sqls/20250620113124-indexes-down.sql
- backend/migrations/sqls/20250620113124-indexes-up.sql
- frontend/codegen.ts
- frontend/gql/graphql.ts
- frontend/src/components/FileTables/GlobalFiles/index.tsx
- frontend/src/components/FileTables/GlobalFiles/query.graphql
- frontend/src/components/FileTables/SharedFiles/index.tsx
- frontend/src/components/FileTables/SharedFiles/query.graphql
- frontend/src/components/FileTables/TrashFiles/index.tsx
- frontend/src/components/FileTables/TrashFiles/query.graphql
- frontend/src/components/FileTables/UserFiles/index.tsx
- frontend/src/components/FileTables/UserFiles/query.graphql
- frontend/src/components/FileTables/common/FileTable/TablePaginator.tsx
- frontend/src/components/FileTables/state.tsx
- frontend/src/utils/async.ts
- frontend/src/utils/auth.ts
This PR tackles some of the performance issues described at #449 
The following changes have been made:
- **Memoized auth session (during 500ms) tokens for reducing the number of calls to auth service**
- **Apply limit to total count of files**: Queries are composed by two parts fetching the N next files + getting the count of total files. This second part had poor performance due to the big amount of files already stored ~90k in taurus. We implemented a dynamic limit that will explore until `10_000` files or `1000` pages beyond the current page, showing `1000+ pages` if that limit is reached.
> Improve query performance

- frontend/src/utils/auth.ts
When I updated the memoization of session in frontend I introduced a bug, creating a memoized callback for each time I called effectively not caching anything.
> fix: memoized frontend session retrieval

- apps/backend/src/app/controllers/object.ts
I misused the `handleInternalError` when it applied to `handleInternalErrorResult` this created a double nested Result object. The returning value of the endpoint was `{value: OffchainMetadata}` when the SDK is expecting just `OffchainMetadata`
Update the error handler `handleInternalErrorResult` for getting a single `Result` object so the returned value is the expected by the SDK
> fix: metadata endpoint

- apps/frontend/src/services/download.ts
- apps/frontend/src/utils/indexedb.ts
Sometimes we experience issues in the downloading service leading to files being downloaded with the incorrect content. This is particularly sensitive because we cache locally files using `IndexedDB` so when a file is downloaded incorrectly any subsequent download of that file is using that incorrect copy. 
Adding a namespace to the `IndexedDB` database for invalidating data once a issue on the download service has been detected.
> Added versioning to local files cache for enabling invalidating

- packages/ui/.eslintrc.json
- packages/ui/.prettierrc
- packages/ui/src/constants/networks.ts
Removes from the network dropdown taurus instance connections. 
Implements the first step of #488
> Remove taurus from auto-drive networks

- apps/frontend/src/components/molecules/FilePreview/index.tsx
There were still references to `AutoDriveNetworkId.Taurus` which provoked build failures
Will disable Taurus from the available networks in [auto-drive frontend](https://explorer.ai3.storage)
> Remove all `AutoDriveNetworkId.Taurus` references

- apps/backend/src/docs/reference/servers.ts
- apps/gateway/public/index.html
- apps/gateway/src/config.ts
- apps/gateway/src/networkComposer.ts
Removed taurus from multi-network gateway and any reference in the landing page
Only mainnet will be available through the gateway
> Remove taurus from multi-network gateway
